server:
  port: 8090
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, fzf
      routes:
        - id: api_route
          uri: http://127.0.0.1:8123
          predicates:
            - Path=/api/**
          filters:
            - name: RequestRateLimiter
              args:
                # 用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
                key-resolver: '#{@UriKeyResolver}'
                redis-rate-limiter.replenishRate: 1 # 令牌桶每秒生成的token速度
                redis-rate-limiter.burstCapacity: 3 # 令牌桶的最大容量
  redis:
    host: localhost
    port: 6379
    database: 0





# 以下配置指定了应用的名称、使用的协议（Dubbo）、注册中心的类型（Nacos）和地址
dubbo:
  application:
    # 设置应用的名称
    name: dubbo-springboot-demo-provider
  # 指定使用 Dubbo 协议，且端口设置为 -1，表示随机分配可用端口
  protocol:
    name: dubbo
    port: 22222
  registry:
    # 配置注册中心为 Nacos，使用的地址是 nacos://localhost:8848
    id: nacos-registry
    address: nacos://localhost:8848



